plugins {
    id 'com.android.application'
    id 'com.chaquo.python' version '12.1.0'
}

android {
    compileSdk 33
    defaultConfig {
        applicationId "com.example.randomguess"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
        ndk { abiFilters "armeabi-v7a" }
        python {
            buildPython "python3"
            pip {}
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
